$lines = Get-Content 'src/app/(tabs)/edit-profile.tsx'
$newMasthead = @(
'        <View style={styles.mastheadSection}>',
'          <View style={[styles.coverBox, { backgroundColor: isDark ? "#1a2e1a" : "#E8F5E9" }]}>',
'            {currentCoverUri ? (',
'              <ExpoImage source={{ uri: currentCoverUri }} style={styles.coverImg} contentFit="cover" />',
'            ) : (',
'              <TouchableOpacity onPress={handlePickCover} style={styles.coverFallback}>',
'                <View style={[styles.coverFallbackIcon, { backgroundColor: G + "20" }]}>',
'                  <Ionicons name="image-outline" size={28} color={G} />',
'                </View>',
'                <Text style={[styles.coverFallbackText, { color: G }]}>Tap to add cover photo</Text>',
'              </TouchableOpacity>',
'            )}',
'            <View style={styles.coverActionIconsRow}>',
'              {currentCoverUri && (',
'                <TouchableOpacity onPress={handleRemoveCover} activeOpacity={0.8} style={[styles.coverIconBtn, { backgroundColor: "rgba(239,68,68,0.85)" }]}>',
'                  <Ionicons name="trash-outline" size={15} color="#FFF" />',
'                </TouchableOpacity>',
'              )}',
'              <TouchableOpacity onPress={handlePickCover} activeOpacity={0.8} style={[styles.coverIconBtn, { backgroundColor: "rgba(0,0,0,0.6)" }]}>',
'                <Ionicons name="camera" size={15} color="#FFF" />',
'              </TouchableOpacity>',
'            </View>',
'          </View>',
'          <View style={styles.avatarOverlapContainer}>',
'            <TouchableOpacity onPress={() => setShowPhotoOptions(true)} activeOpacity={0.85} style={[styles.avatarWrap, { borderColor: BG }]}>',
'              <Avatar url={localAvatarUri ?? user.avatarUrl} name={user.displayName} size={96} />',
'              <View style={[styles.avatarCameraBadge, { backgroundColor: G, borderColor: BG }]}>',
'                <Ionicons name="camera" size={14} color="#FFF" />',
'              </View>',
'            </TouchableOpacity>',
'            <Text style={[styles.avatarName, { color: TEXT }]}>{user.displayName}</Text>',
'            <Text style={[styles.avatarHandle, { color: TEXT3 }]}>@{user.username || "username"}</Text>',
'            {photoError ? <Text style={styles.errorBannerText}>{photoError}</Text> : null}',
'          </View>',
'          <View style={[styles.completionCard, { backgroundColor: SURF, borderColor: BORDER }]}>',
'            <View style={styles.completionRow}>',
'              <View style={[styles.completionIconBox, { backgroundColor: G + "15" }]}>',
'                <Ionicons name="stats-chart" size={14} color={G} />',
'              </View>',
'              <Text style={[styles.completionLabel, { color: TEXT }]}>Profile Completion</Text>',
'              <Text style={[styles.completionPct, { color: G }]}>{completionPct}%</Text>',
'            </View>',
'            <View style={[styles.completionTrack, { backgroundColor: isDark ? "rgba(255,255,255,0.08)" : "#E8F5E9" }]}>',
'              <View style={[styles.completionFill, { width: `${completionPct}%` as any, backgroundColor: G }]} />',
'            </View>',
'            {completionPct < 100 && (',
'              <Text style={[styles.completionHint, { color: TEXT3 }]}>Fill in all sections to unlock full community features</Text>',
'            )}',
'          </View>',
'        </View>'
)
$result = $lines[0..436] + $newMasthead + $lines[492..($lines.Length-1)]
Set-Content 'src/app/(tabs)/edit-profile.tsx' $result
Write-Host 'DONE'
