import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiClient } from './client';

export type HelpCategory = 'Blood Donation' | 'Medical Assistance' | 'Education' | 'Job Referral' | 'Other Community Help';
export const HELP_CATEGORIES: { id: HelpCategory; label: string; icon: string; emoji: string; color: string }[] = [
  { id: 'Blood Donation', label: 'Blood Donation', icon: 'water', emoji: '🩸', color: '#DC2626' }, { id: 'Medical Assistance', label: 'Medical Assistance', icon: 'medkit', emoji: '🏥', color: '#059669' }, { id: 'Education', label: 'Education', icon: 'school', emoji: '🎓', color: '#2563EB' }, { id: 'Job Referral', label: 'Job Referral', icon: 'briefcase', emoji: '💼', color: '#9333EA' }, { id: 'Other Community Help', label: 'Other Help', icon: 'heart', emoji: '🤝', color: '#D97706' },
];
export type HelpUrgency = 'NORMAL' | 'URGENT'; export type HelpStatus = 'PENDING' | 'APPROVED' | 'REJECTED' | 'RESOLVED'; export type ContactPreference = 'IN_APP' | 'WHATSAPP' | 'PHONE';
export interface HelperOffer { id: string; requestId: string; helperId: string; helperName: string; helperAvatarUrl?: string; helperPhone?: string; message?: string; offeredAt: string; }
export interface HelpReport { id: string; requestId: string; reportedBy: string; reason: 'Fake / Suspicious' | 'Incorrect Information' | 'Inappropriate Content' | 'Other'; details?: string; reportedAt: string; }
export interface HelpRequest { id: string; userId: string; requesterName: string; requesterAvatarUrl?: string; requesterLocation: string; requesterPhone?: string; category: HelpCategory; title: string; description: string; location: string; urgency: HelpUrgency; contactPreference: ContactPreference; status: HelpStatus; rejectionReason?: string | null; helpers: HelperOffer[]; reports: HelpReport[]; createdAt: string; resolvedAt?: string | null; }
export interface HelpFilters { category?: string; urgency?: HelpUrgency; search?: string; }
const unwrap = <T,>(r: any) => (r.data?.data ?? r.data) as T;
const invalidate = (qc: ReturnType<typeof useQueryClient>) => { qc.invalidateQueries({ queryKey: ['help-requests'] }); qc.invalidateQueries({ queryKey: ['admin-help-requests'] }); };
export function usePublicHelpRequestsQuery(filters?: HelpFilters) { return useQuery({ queryKey: ['help-requests', 'public', filters], queryFn: async () => unwrap<HelpRequest[]>(await apiClient.get('/help-requests', { params: filters })) }); }
export function useHelpRequestQuery(id: string) { return useQuery({ queryKey: ['help-request', id], queryFn: async () => unwrap<HelpRequest>(await apiClient.get(`/help-requests/${id}`)), enabled: !!id }); }
export function useMyHelpRequestsQuery() { return useQuery({ queryKey: ['help-requests', 'mine'], queryFn: async () => unwrap<HelpRequest[]>(await apiClient.get('/help-requests/mine')) }); }
export function useCreateHelpRequestMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: async (data: { category: HelpCategory; title: string; description: string; location: string; urgency: HelpUrgency; contactPreference: ContactPreference; userName: string; userLocation: string; userPhone?: string }) => unwrap<HelpRequest>(await apiClient.post('/help-requests', data)), onSuccess: () => invalidate(qc) }); }
export function useOfferHelpMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ requestId, message }: { requestId: string; helperName?: string; helperAvatarUrl?: string; helperPhone?: string; message?: string }) => unwrap<HelperOffer>(await apiClient.post(`/help-requests/${requestId}/offers`, { message })), onSuccess: (_, v) => { invalidate(qc); qc.invalidateQueries({ queryKey: ['help-request', v.requestId] }); } }); }
export function useResolveHelpRequestMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: async (id: string) => unwrap(await apiClient.patch(`/help-requests/${id}/resolve`)), onSuccess: () => invalidate(qc) }); }
export function useReportHelpRequestMutation() { return useMutation({ mutationFn: async () => { throw new Error('Request reporting endpoint is not available yet'); } }); }
export function useAdminHelpRequestsQuery(statusTab?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'REPORTED' | 'RESOLVED') { return useQuery({ queryKey: ['admin-help-requests', statusTab], queryFn: async () => unwrap<HelpRequest[]>(await apiClient.get('/help-requests/admin', { params: statusTab && statusTab !== 'REPORTED' ? { status: statusTab } : {} })) }); }
export function useAdminApproveHelpMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: async (id: string) => unwrap(await apiClient.patch(`/help-requests/${id}/moderate`, { status: 'APPROVED' })), onSuccess: () => invalidate(qc) }); }
export function useAdminRejectHelpMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, reason }: { id: string; reason: string }) => unwrap(await apiClient.patch(`/help-requests/${id}/moderate`, { status: 'REJECTED', reason })), onSuccess: () => invalidate(qc) }); }
export function useAdminDismissReportsMutation() { return useMutation({ mutationFn: async () => { throw new Error('Request reporting endpoint is not available yet'); } }); }
export function useAdminDeleteHelpMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: async (id: string) => { await apiClient.delete(`/help-requests/${id}`); }, onSuccess: () => invalidate(qc) }); }
