import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiClient } from './client';
export type StoryCategory = 'Achievements' | 'Business & Entrepreneurship' | 'Education' | 'Sports' | 'Community Service' | 'Inspiring Journeys';
export const STORY_CATEGORIES: { id: StoryCategory; label: string; emoji: string; color: string }[] = [{ id: 'Achievements', label: 'Achievements', emoji: '🏆', color: '#D97706' }, { id: 'Business & Entrepreneurship', label: 'Business', emoji: '💼', color: '#059669' }, { id: 'Education', label: 'Education', emoji: '🎓', color: '#2563EB' }, { id: 'Sports', label: 'Sports', emoji: '🏅', color: '#DC2626' }, { id: 'Community Service', label: 'Community Service', emoji: '🌱', color: '#16A34A' }, { id: 'Inspiring Journeys', label: 'Inspiring Journeys', emoji: '🌟', color: '#9333EA' }];
export type StoryStatus = 'DRAFT' | 'PUBLISHED' | 'UNPUBLISHED';
export interface CommunityStory { id: string; title: string; personName: string; personAvatarUrl?: string; profession: string; location: string; category: StoryCategory; shortDescription: string; fullStory: string; featuredImage: string; additionalImages?: string[]; isFeatured: boolean; status: StoryStatus; publishedAt: string; createdAt: string; readTimeMinutes: number; }
export interface StoryFilters { category?: string; search?: string; featuredOnly?: boolean; }
const unwrap = <T,>(r: any) => (r.data?.data ?? r.data) as T;
const invalidate = (qc: ReturnType<typeof useQueryClient>) => { qc.invalidateQueries({ queryKey: ['community-stories'] }); qc.invalidateQueries({ queryKey: ['admin-stories'] }); };
export function usePublicStoriesQuery(filters?: StoryFilters) { return useQuery({ queryKey: ['community-stories', 'public', filters], queryFn: async () => unwrap<CommunityStory[]>(await apiClient.get('/community-stories', { params: filters })) }); }
export function useFeaturedStoriesQuery() { return usePublicStoriesQuery({ featuredOnly: true }); }
export function useStoryQuery(id: string) { return useQuery({ queryKey: ['community-story', id], queryFn: async () => unwrap<CommunityStory>(await apiClient.get(`/community-stories/${id}`)), enabled: !!id }); }
export function useAdminStoriesQuery(statusTab?: StoryStatus | 'ALL') { return useQuery({ queryKey: ['admin-stories', statusTab], queryFn: async () => unwrap<CommunityStory[]>(await apiClient.get('/community-stories/admin', { params: statusTab && statusTab !== 'ALL' ? { status: statusTab } : {} })) }); }
export function useAdminCreateStoryMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: async (data: Omit<CommunityStory, 'id' | 'createdAt' | 'readTimeMinutes'>) => unwrap<CommunityStory>(await apiClient.post('/community-stories', data)), onSuccess: () => invalidate(qc) }); }
export function useAdminUpdateStoryMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, data }: { id: string; data: Partial<CommunityStory> }) => unwrap<CommunityStory>(await apiClient.patch(`/community-stories/${id}`, data)), onSuccess: (_, v) => { invalidate(qc); qc.invalidateQueries({ queryKey: ['community-story', v.id] }); } }); }
export function useAdminTogglePublishMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, status }: { id: string; status: StoryStatus }) => unwrap(await apiClient.patch(`/community-stories/${id}`, { status })), onSuccess: () => invalidate(qc) }); }
export function useAdminToggleFeaturedMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: async ({ id, isFeatured }: { id: string; isFeatured: boolean }) => unwrap(await apiClient.patch(`/community-stories/${id}`, { isFeatured })), onSuccess: () => invalidate(qc) }); }
export function useAdminDeleteStoryMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: async (id: string) => { await apiClient.delete(`/community-stories/${id}`); }, onSuccess: () => invalidate(qc) }); }
